// flow-typed signature: 79ec60ed0ba4dfba1435e9aba0f50f22
// flow-typed version: <<STUB>>/grpc_v1.24.2/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grpc' {
  declare module.exports: any;
}
