// flow-typed signature: 746c38a531bfff0cf8f06444cefbdabe
// flow-typed version: <<STUB>>/@grpc/proto-loader_v0.5.3/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@grpc/proto-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@grpc/proto-loader' {
  declare module.exports: any;
}
