// flow-typed signature: f764f7d49a538eaa778a06d249f7817f
// flow-typed version: <<STUB>>/pino_v5.15.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pino'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pino' {
  declare module.exports: any;
}
